### ISSUE TITLE
Do you have an estimate of number of concurrent connections per RADAR server?

### ISSUE THREAD

**Issue by raygerami** [zendesk/radar#119]
FYI: we did some experiment with socket.io servers and maxed 26000 concurrent connections, from which point we started getting disconnection from some clients, so  I would say we could support 10,000 solid concurrent connections per socket.io servers on descent machines.

Do you have any benchmark on concurrent connections per RADAR servers?
Thanks

**Comment by vanchi-zendesk** [comment]
Unfortunately, no such benchmark exists at the moment. Beyond the number of concurrent connections, we should also measure the number of messages that can be processed per server too. If you decide to try it out, please do let us know the results.

**Comment by samshull** [comment]
Radar is also built around the premise that you can add more application servers to a cluster in order to increase the total number of concurrent connections in the cluster without concern for the number of concurrent connections on an individual application server. However, this increases the latency and decreases the performance of distributing the messages to some extent.
